apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.100.71
  - ip: 192.168.100.72
  - ip: 192.168.100.73
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP

