apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: kube-system
spec:
  ports:
  - name: port
    port: 2379
    protocol: TCP
  type: ClusterIP
  clusterIP: None
#spec:
#  selector:
#    component: etcd
#  type: ClusterIP
#  clusterIP: None
#  ports:
#  - name: port
#    port: 2379
#    targetPort: 2379
#    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 200.200.100.71
    nodeName: etcd00
  - ip: 200.200.100.72
    nodeName: etcd01
  - ip: 200.200.100.73
    nodeName: etcd02
  ports:
  - name: port
    port: 2379
    protocol: TCP
